import fs from 'fs/promises';
import path from 'path';
import { CONFIG } from './config.js';

/**
 * Generate a Markdown competitive intelligence report.
 */
export async function generateMarkdownReport(scrapedData, outputDir) {
  const date = new Date().toISOString().split('T')[0];
  const filename = `report-${date}.md`;
  const filepath = path.join(outputDir, filename);

  let md = '';

  // Header
  md += `# Competitive Intelligence Report\n\n`;
  md += `**Prepared for:** ${CONFIG.company.name}\n`;
  md += `**Date:** ${date}\n`;
  md += `**Competitors analyzed:** ${scrapedData.length}\n\n`;
  md += `---\n\n`;

  // Per-competitor breakdown
  md += `# Competitor Details\n\n`;

  for (const data of scrapedData) {
    md += `## ${data.competitor.name}\n\n`;
    md += `**Website:** ${data.competitor.url}\n\n`;

    // Website data
    if (data.website) {
      if (data.website.error) {
        md += `> Website scrape failed: ${data.website.error}\n\n`;
      } else {
        md += `### Website Overview\n\n`;
        md += `- **Title:** ${data.website.title || 'N/A'}\n`;
        md += `- **Description:** ${data.website.metaDescription || 'N/A'}\n\n`;

        if (data.website.headings?.length) {
          md += `**Key Headings:**\n\n`;
          for (const h of data.website.headings) {
            md += `- ${h.text}\n`;
          }
          md += `\n`;
        }

        if (data.website.bodyText) {
          md += `<details>\n<summary>Website Text Excerpt</summary>\n\n`;
          md += `${data.website.bodyText.substring(0, 3000)}\n\n`;
          md += `</details>\n\n`;
        }

        if (data.website.screenshot) {
          const relPath = path.relative(outputDir, data.website.screenshot).replace(/\\/g, '/');
          md += `**Homepage Screenshot:** ![${data.competitor.name} website](${relPath})\n\n`;
        }
      }
    }

    // LinkedIn Ads
    md += `### LinkedIn Ad Library\n\n`;
    if (data.linkedinAds?.error) {
      md += `> ${data.linkedinAds.error}\n\n`;
    } else if (data.linkedinAds?.adCount) {
      md += `- **Results:** ${data.linkedinAds.adCount}\n\n`;
    } else {
      md += `- Results captured in screenshot\n\n`;
    }
    if (data.linkedinAds?.screenshot) {
      const relPath = path.relative(outputDir, data.linkedinAds.screenshot).replace(/\\/g, '/');
      md += `![${data.competitor.name} LinkedIn Ads](${relPath})\n\n`;
    }

    // Google Ads
    md += `### Google Ads Transparency\n\n`;
    if (data.googleAds?.error) {
      md += `> ${data.googleAds.error}\n\n`;
    } else {
      md += `- **Active Ads:** ${data.googleAds?.hasAds ? 'Yes' : 'No / Not found'}\n\n`;
    }
    if (data.googleAds?.screenshot) {
      const relPath = path.relative(outputDir, data.googleAds.screenshot).replace(/\\/g, '/');
      md += `![${data.competitor.name} Google Ads](${relPath})\n\n`;
    }

    md += `---\n\n`;
  }

  // Footer
  md += `\n*Report generated by CI Agent for ${CONFIG.company.name} on ${date}*\n`;

  await fs.writeFile(filepath, md, 'utf-8');
  console.log(`[report] Markdown report saved: ${filepath}`);
  return filepath;
}
